### ISSUE TITLE
Dimensional Modelling for Data Warehouse

### ISSUE THREAD

**Issue by renuka-fernando** [renuka-fernando/diabetes_data_warehouse#1]
@JayathmaChathurangani
Continue dimensional modeling for the data warehouse
Edit `dimensional_modeling/dimentional_design.xml` file using draw.io

**Comment by JayathmaChathurangani** [comment]
Then shall remove the dim_diagnosis and leave those attributes in the fact?

**Comment by JayathmaChathurangani** [comment]
Added Dimension tables test and medication. Changed the attributes in the rest of the dimension tables and the fact table. Then updated the README with the new design diagram.

**Comment by JayathmaChathurangani** [comment]
fixed the issue #6

**Comment by renuka-fernando** [comment]
Let's mention what are the 24 fields in ***dim_medication***.
