### ISSUE TITLE
Data Cleansing

### ISSUE THREAD

**Issue by renuka-fernando** [renuka-fernando/diabetes_data_warehouse#12]
Cleansing patient's gender

| encounter_id | patient_nbr | race      | gender |
|--------------|-------------|-----------|--------|
|     20729328 |    55500588 | Caucasian | Female |
|     96312942 |    55500588 | Caucasian | Male   |
|    183845022 |   109210482 | Caucasian | Female |
|    186533256 |   109210482 | Caucasian | Male   |
|    220872936 |    40867677 | ?         | Male   |
|    232356060 |    40867677 | ?         | Female |
|    291975978 |    40867677 | ?         | Male   |

Select most frequent and latest data.

**Comment by renuka-fernando** [comment]
Make them all 'Male' as with selecting most frequent and latest data.
Clean with
```sql
UPDATE `diabetes_dwh_staging`.`dataset`
SET `gender` = 'Male'
WHERE `patient_nbr` in (55500588, 109210482, 40867677);
```

**Comment by JayathmaChathurangani** [comment]
+1
