### ISSUE TITLE
Cleansing patient race

### ISSUE THREAD

**Issue by renuka-fernando** [renuka-fernando/diabetes_data_warehouse#13]
I have created views for dirty data wrt race of the patient.(see `data_cleansing/data_cleansing_patients_race.sql`)

@JayathmaChathurangani
1. Select these data.
1. Update these dirty data with most frequent race, otherwise the latest one (which have largest `encounter_id`).
1. Edit update queries.

I have done an example.

*** Related Issues
https://github.com/renuka-fernando/diabetes_data_warehouse/issues/12

**Comment by JayathmaChathurangani** [comment]
The following records were dirty data wrt to race of patient. My plan for update is given as well.
C - Caucasian, AA - AfricanAmerican, O - Other, A -Asian, H - Hispanic

  | patient_nbr | No. of races | Respective frequency in the   order of occurance | Total frequency | Update Race to
-- | -- | -- | -- | -- | --
  | 1553220 | 2 | AA C | 2 | C
  | 6919587 | 2 | C AA | 2 | AA
  | 10980891 | 2 | C AA | 2 | AA
  | 23724792 | 2 | O C | 2 | C
  | 24332220 | 2 | C A | 2 | A
  | 28532295 | 2 | H3 O3 | 6 | O
  | 30689766 | 2 | H O | 2 | O
  | 31812075 | 2 | O A | 2 | A
  | 32314608 | 2 | A O | 2 | O
  | 33247647 | 2 | C O | 2 | O
  | 34248078 | 2 | O A2 | 3 | A
  | 36967347 | 2 | O2 A | 3 | O
  | 37547937 | 2 | H2 O3 | 5 | O
  | 37572957 | 2 | O H | 2 | H
  | 37638306 | 2 | O2 A | 3 | O
  | 38774187 | 2 | H O2 | 3 | O
  | 38893887 | 2 | A C3 | 4 | C
  | 39160719 | 2 | O4 A | 5 | O
  | 40090752 | 2 | C AA2 | 3 | AA
  | 42096384 | 2 | H O | 2 | O
  | 42246738 | 2 | AA C | 2 | C
  | 44744166 | 2 | H2 O | 3 | H
  | 45113778 | 2 | C H | 2 | H
  | 52316388 | 2 | AA C2 | 3 | C
  | 54643194 | 2 | C AA | 2 | AA
  | 90035874 | 2 | O H2 | 3 | H
  | 90817893 | 2 | AA O | 2 | O
  | 91107549 | 2 | H7 O2 | 9 | H
  | 93105117 | 2 | H O | 2 | O
  | 93662784 | 2 | H O | 2 | O
  | 93809358 | 2 | H5 O | 6 | H
  | 94027644 | 2 | A O | 2 | O
  | 94088088 | 2 | C H | 2 | H
  | 94539465 | 2 | O2 A2 | 4 | A
  | 97024806 | 2 | C A | 2 | A
  | 98584524 | 2 | C2 O2 | 4 | O
  | 98934615 | 2 | C H | 2 | H
  | 100322946 | 2 | H O2 | 3 | O
  | 101753730 | 2 | C AA | 2 | AA
  | 103228398 | 2 | H O | 2 | O
  | 103305528 | 2 | C A10 | 11 | A
  | 103690161 | 2 | O2 A | 3 | O
  | 104622570 | 2 | O A2 | 3 | A
  | 105125598 | 2 | H O | 2 | O
  | 106425234 | 2 | O2 A | 3 | O
  | 106895331 | 3 | H2 AA O H | 5 | H
  | 107849052 | 3 | O A AA | 3 | AA
  | 109448541 | 2 | H7 O6 | 13 | H
  | 110657970 | 2 | O A | 2 | A
  | 111534210 | 2 | O A | 2 | A
  | 112367349 | 2 | H C3 | 4 | C
Total | 51 |   |   | 167 |
