### ISSUE TITLE
Update MySQL Workbench Model for DWH tables

### ISSUE THREAD

**Issue by renuka-fernando** [renuka-fernando/diabetes_data_warehouse#7]
@Piyushani-Sewwandi
Update '***diabetes_data_warehouse/data_warehouse.mwb***' file with creating tables for dimensions and fact tables.

**Comment by Piyushani-Sewwandi** [comment]
created dimension tables

**Comment by renuka-fernando** [comment]
Some modifications
- Needed to be added the fact table also
- SK should be added to each dimension and make it ***primary key*** and ***auto increment***.
- Make business key ***not null*** and ***unique***.
- In ***dim_medication*** the ***24_fields_of_medication*** need to be replaced with that 24 fields. (dimensional model also need to be changed https://github.com/renuka-fernando/diabetes_data_warehouse/issues/1).

example ***dim_patient***
![dim_patient](https://user-images.githubusercontent.com/23183042/42012553-7803569a-7ab6-11e8-856c-11b646c64777.PNG)

**Comment by Piyushani-Sewwandi** [comment]
fact table and SKs are added. 24_fields_of_medication field replaced with the 24 fields of medications.
