### ISSUE TITLE
Transform Data

### ISSUE THREAD

**Issue by renuka-fernando** [renuka-fernando/diabetes_data_warehouse#9]
### Load patients to DWH using
```sql
INSERT INTO `diabetes_dwh`.`dim_patient`(`patient_number`, `race`, `gender`, `age`, `weight`)
SELECT DISTINCT `patient_nbr`, `race`, `gender`, `age`, `weight`
FROM `diabetes_dwh_staging`.`dataset`;
```
Result
`Error Code: 1062. Duplicate entry '2341521' for key 'patient_number_UNIQUE'`

### Select the patient with ***patient_nbr*** = 2341521 (without `DISTINCT `).
```sql
SELECT `patient_nbr`, `race`, `gender`, `age`, `weight`
FROM `diabetes_dwh_staging`.`dataset`
WHERE `patient_nbr` = 2341521;
```
| patient_nbr | race            | gender | age     | weight |
|-------------|--------------|--------|----------|------------|
|     2341521 | ?               | Female | [70-80) | ?   |  
|     2341521 | AfricanAmerican | Female | [70-80) | ?      |
|     2341521 | AfricanAmerican | Female | [70-80) | ?      |
|     2341521 | AfricanAmerican | Female | [70-80) | ?      |
|     2341521 | AfricanAmerican | Female | [70-80) | ?      |
|     2341521 | AfricanAmerican | Female | [70-80) | ?      |

In one record race of the patient is missing.

### In the data set
- race: 2% missing
- weight: 97% missing -> ignore weight
- age format: "[x-x)" -> to columns with `ageFrom` and `ageTo`.
- If the same patient admits after a long time, they may be in different age range.

**Comment by renuka-fernando** [comment]
There is an instance for the above issue (different age ranges)

| patient_nbr | race            | gender | age     | weight |
|--------------|---------------|---------|---------|------|
|     1061811 | AfricanAmerican | Female | [50-60) | ?      |
|     1061811 | AfricanAmerican | Female | [50-60) | ?      |
|     1061811 | AfricanAmerican | Female | [60-70) | ?      |
|     1061811 | AfricanAmerican | Female | [60-70) | ?      |
|     1061811 | AfricanAmerican | Female | [60-70) | ?      |

| patient_nbr | race      | gender | age     | weight |
|-------------|-----------|--------|---------|--------|
|      688347 | Caucasian | Female | [50-60) | ?      |
|      688347 | Caucasian | Female | [60-70) | ?      |
### Options
1. Move age (and weight) to fact table.
1. Add another row with different SK.

**Comment by renuka-fernando** [comment]
Races = {Caucasian, AfricanAmerican, ?, Other, Asian, Hispanic}
Other instances with different races

| patient_nbr | race      | gender | age     | weight |
|-------------|-----------|--------|---------|--------|
|    70269183 | Hispanic  | Female | [60-70) | ?      |
|    70269183 | Caucasian | Female | [60-70) | ?      |

| patient_nbr | race      | gender | age     | weight |
 |-------------|-----------|--------|---------|--------|
|    83158605 | Hispanic | Male   | [60-70) | ?      |
|    83158605 | Asian    | Male   | [60-70) | ?      |

| patient_nbr | race      | gender | age     | weight |
|-------------|-----------|--------|---------|--------|
|    12027024 | Other     | Male   | [40-50) | ?      |
|    12027024 | Other     | Male   | [40-50) | ?      |
|    12027024 | Caucasian | Male   | [50-60) | ?      |
|    12027024 | Caucasian | Male   | [50-60) | ?      |

**Comment by renuka-fernando** [comment]
Gender = {Female, Male, Unknown/Invalid}
Inconsistency in gender (patients with id = 55500588, 109210482, 40867677 only)

```sql
SELECT `patient_nbr`
FROM `diabetes_dwh_staging`.`dataset`
WHERE `patient_nbr` in (
	SELECT F.`patient_nbr`
	FROM `diabetes_dwh_staging`.`dataset` as F
	WHERE F.`gender` = 'Female'
) AND `patient_nbr` in (
	SELECT M.`patient_nbr`
	FROM `diabetes_dwh_staging`.`dataset` as M
	WHERE M.`gender` = 'Male'
)
```

| patient_nbr | race      | gender | age     | weight |
|-------------|-----------|--------|---------|--------|
|    55500588 | Caucasian | Female | [70-80) | ?      |
|    55500588 | Caucasian | Male   | [80-90) | ?      |

| patient_nbr | race      | gender | age     | weight |
|-------------|-----------|--------|---------|--------|
|   109210482 | Caucasian | Female | [50-60) | ?      |
|   109210482 | Caucasian | Male   | [50-60) | ?      |

| patient_nbr | race | gender | age     | weight |
|-------------|------|--------|---------|--------|
|    40867677 | ?    | Male   | [40-50) | ?      |
|    40867677 | ?    | Female | [40-50) | ?      |
|    40867677 | ?    | Male   | [40-50) | ?      |

No any patient with ('Unknown/Invalid' and 'Male') or ('Unknown/Invalid' and Female')

**Comment by JayathmaChathurangani** [comment]
PR #14 resolved the issue related to patient race
